curl -o introduction-to-academy.html https://academy.hackthebox.com/course/preview/introduction-to-academy
curl -o learning-process.html https://academy.hackthebox.com/course/preview/learning-process
curl -o hacking-wordress.html https://academy.hackthebox.com/course/preview/hacking-wordpress
curl -o linux-fundamentals.html https://academy.hackthebox.com/course/preview/linux-fundamentals
curl -o network-enumeration-with-nmap.html https://academy.hackthebox.com/course/preview/network-enumeration-with-nmap
curl -o cracking-passwords-with-hashcat.html https://academy.hackthebox.com/course/preview/cracking-passwords-with-hashcat
curl -o active-directory-ldap.html https://academy.hackthebox.com/course/preview/active-directory-ldap
curl -o introduction-to-bash-scripting.html https://academy.hackthebox.com/course/preview/introduction-to-bash-scripting
curl -o file-transfers.html https://academy.hackthebox.com/course/preview/file-transfers
curl -o kerberos-attacks.html  https://academy.hackthebox.com/course/preview/kerberos-attacks
curl -o dns-enumeration-using-python.html https://academy.hackthebox.com/course/preview/dns-enumeration-using-python
curl -o osint-corporate-recon.html https://academy.hackthebox.com/course/preview/osint-corporate-recon
curl -o stack-based-buffer-overflows-on-linux-x86.html https://academy.hackthebox.com/course/preview/stack-based-buffer-overflows-on-linux-x86
curl -o sql-injection.html https://academy.hackthebox.com/course/preview/sql-injection-fundamentals
curl -o introduction-to-networking.html https://academy.hackthebox.com/course/preview/introduction-to-networking
curl -o web-requests.html https://academy.hackthebox.com/course/preview/web-requests
curl -o secure-coding-101-with-javascript.html https://academy.hackthebox.com/course/preview/secure-coding-101-javascript
curl -o using-the-metasploit-framework.html https://academy.hackthebox.com/course/preview/using-the-metasploit-framework
curl -o javascript-deobfuscation.html https://academy.hackthebox.com/course/preview/javascript-deobfuscation
curl -o whitebox-pentesting-101-command-injection.html https://academy.hackthebox.com/course/preview/whitebox-pentesting-101-command-injection
curl -o windows-fundamentals.html https://academy.hackthebox.com/course/preview/windows-fundamentals
curl -o linux-privilege-escalation.html https://academy.hackthebox.com/course/preview/linux-privilege-escalation
curl -o attacking-web-applications-with-ffuf.html https://academy.hackthebox.com/course/preview/attacking-web-applications-with-ffuf
curl -o login-brute-forcing.html https://academy.hackthebox.com/course/preview/login-brute-forcing
curl -o sqlmap-essentials.html https://academy.hackthebox.com/course/preview/sqlmap-essentials
curl -o windows-privilege-escalation.html https://academy.hackthebox.com/course/preview/windows-privilege-escalation
curl -o active-directory-powerview.html https://academy.hackthebox.com/course/preview/active-directory-powerview
curl -o active-directory-bloodhound.html https://academy.hackthebox.com/course/preview/active-directory-bloodhound
curl -o introduction-active-directory.html https://academy.hackthebox.com/course/preview/introduction-to-active-directory
curl -o introduction-to-web-applications.html https://academy.hackthebox.com/course/preview/introduction-to-web-applications
curl -o getting-started.html https://academy.hackthebox.com/course/preview/getting-started
curl -o broken-authentication.html https://academy.hackthebox.com/course/preview/broken-authentication
curl -o intro-to-network-traffic-analysis.html https://academy.hackthebox.com/course/preview/intro-to-network-traffic-analysis
curl -o using-crackmap-exec https://academy.hackthebox.com/course/preview/using-crackmapexec
curl -o intro-to-assembly-language.html https://academy.hackthebox.com/course/preview/intro-to-assembly-language
curl -o setting-up.html https://academy.hackthebox.com/course/preview/setting-up
curl -o introduction-to-python3.html https://academy.hackthebox.com/course/preview/introduction-to-python-3
curl -o stack-based-buffer-overflow-on-windows-x86.html https://academy.hackthebox.com/course/preview/stack-based-buffer-overflows-on-windows-x86
curl -o penetration-testing-process.html https://academy.hackthebox.com/course/preview/penetration-testing-process
curl -o cross-site-scripting.html https://academy.hackthebox.com/course/preview/cross-site-scripting-xss
curl -o vulnerability-assestment.html https://academy.hackthebox.com/course/preview/vulnerability-assessment
curl -o command-injections.html https://academy.hackthebox.com/course/preview/command-injections
curl -o using-web-proxies.html https://academy.hackthebox.com/course/preview/using-web-proxies
curl -o footprinting.html https://academy.hackthebox.com/course/preview/footprinting
curl -o attacking-common-application.html https://academy.hackthebox.com/course/preview/attacking-common-applications
curl -o shells-payloads.html https://academy.hackthebox.com/course/preview/shells--payloads
curl -o attacking-common-services.html https://academy.hackthebox.com/course/preview/attacking-common-services
curl -o web-attacks.html https://academy.hackthebox.com/course/preview/web-attacks
curl -o file-upload-attacks.html https://academy.hackthebox.com/course/preview/file-upload-attacks
curl -o active-directory-enumertion-attacks.html https://academy.hackthebox.com/course/preview/active-directory-enumeration--attacks
curl -o information-gathering-web-edition.html https://academy.hackthebox.com/course/preview/information-gathering---web-edition
curl -o server-side-attacks.html https://academy.hackthebox.com/course/preview/server-side-attacks
curl -o password-attacks.html https://academy.hackthebox.com/course/preview/password-attacks
curl -o incident-handling-process.html https://academy.hackthebox.com/course/preview/incident-handling-process
curl -o session-security.html https://academy.hackthebox.com/course/preview/session-security
curl -o mac-os-fundamentals.html https://academy.hackthebox.com/course/preview/macos-fundamentals
curl -o pivoting-tunneling-and-port-forwarding.html https://academy.hackthebox.com/course/preview/pivoting-tunneling-and-port-forwarding
curl -o web-service-api-attacks.html https://academy.hackthebox.com/course/preview/web-service--api-attacks
curl -o bug-bounty-hunting-process.html https://academy.hackthebox.com/course/preview/bug-bounty-hunting-process
curl -o documentation-and-reporting.html https://academy.hackthebox.com/course/preview/documentation--reporting
curl -o attacking-enterprise-network.html https://academy.hackthebox.com/course/preview/attacking-enterprise-networks
curl -o introduction-to-windows-command-line.html https://academy.hackthebox.com/course/preview/introduction-to-windows-command-line
curl -o introduction-to-deserialization-attacks.html https://academy.hackthebox.com/course/preview/introduction-to-deserialization-attacks
curl -o attacking-authentication-mechanisms.html https://academy.hackthebox.com/course/preview/attacking-authentication-mechanisms
curl -o introduction-to-nosql-injection.html https://academy.hackthebox.com/course/preview/introduction-to-nosql-injection
curl -o windows-attack-and-defense.html https://academy.hackthebox.com/course/preview/windows-attacks--defense
curl -o blind-sql-injection.html https://academy.hackthebox.com/course/preview/blind-sql-injection
curl -o game-hacking-fundamentals.html https://academy.hackthebox.com/course/preview/game-hacking-fundamentals
curl -o http-tls-attacks.html https://academy.hackthebox.com/course/preview/httpstls-attacks
curl -o advanced-sql-injections.html https://academy.hackthebox.com/course/preview/advanced-sql-injections
curl -o abusing-http-misconfigurations.html https://academy.hackthebox.com/course/preview/abusing-http-misconfigurations
curl -o http-attacks.html https://academy.hackthebox.com/course/preview/http-attacks
curl -o injection-attacks.html https://academy.hackthebox.com/course/preview/injection-attacks
curl -o white-box-attacks.html https://academy.hackthebox.com/course/preview/whitebox-attacks
curl -o security-monitoring-siem.html https://academy.hackthebox.com/course/preview/security-monitoring--siem-fundamentals
curl -o introduction-to-threat-hunting.html https://academy.hackthebox.com/course/preview/introduction-to-threat-hunting--hunting-with-elastic
curl -o windows-event-log.html https://academy.hackthebox.com/course/preview/windows-event-logs--finding-evil
curl -o understanding-log-sources.html https://academy.hackthebox.com/course/preview/understanding-log-sources--investigating-with-splunk
curl -o dacl-attacks-i.html https://academy.hackthebox.com/course/preview/dacl-attacks-i




